#!/usr/bin/env bash
#
# build_shaders.sh — compile trajviz GLSL shaders to SPIR-V and embed
# them as uint32_t arrays in ../shaders.c.
#
# Run from anywhere — the script cds into its own directory first.
# Invoked automatically by setup.py before building the trajviz Python
# extension. Safe to run by hand for shader iteration:
#
#     cd pufferlib/ocean/drive/trajviz/shaders && ./build_shaders.sh
#
# Requires: glslangValidator (apt: glslang-tools), python3.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

GLSLANG="${GLSLANG:-glslangValidator}"
if ! command -v "$GLSLANG" >/dev/null 2>&1; then
    echo "ERROR: $GLSLANG not found. Install with: sudo apt install glslang-tools" >&2
    exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
    echo "ERROR: python3 not found." >&2
    exit 1
fi

OUT_C="../shaders.c"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# Names match the externs declared in shaders.h. Order is significant only
# for the generated file's readability.
SHADER_NAMES=(polyline_vert polyline_frag agent_box_vert agent_box_frag)
SHADER_SRCS=(polyline.vert  polyline.frag  agent_box.vert  agent_box.frag)

for i in "${!SHADER_NAMES[@]}"; do
    name="${SHADER_NAMES[$i]}"
    src="${SHADER_SRCS[$i]}"
    "$GLSLANG" -V "$src" -o "$TMPDIR/${name}.spv" >/dev/null
done

# Emit shaders.c. Using python3 for the hex dump because it's portable
# and supports unpacking little-endian uint32 cleanly. The 16-byte
# alignment annotation is required by Vulkan's vkCreateShaderModule
# (pCode must be uint32-aligned; 16 covers any reasonable allocator).
{
    echo "/* AUTO-GENERATED by shaders/build_shaders.sh — do not edit. */"
    echo "#include <stddef.h>"
    echo "#include <stdint.h>"
    echo
    for i in "${!SHADER_NAMES[@]}"; do
        name="${SHADER_NAMES[$i]}"
        spv="$TMPDIR/${name}.spv"
        size=$(wc -c < "$spv")
        echo "const uint32_t ${name}_spv[] __attribute__((aligned(16))) = {"
        python3 -c "
import struct, sys
data = open(sys.argv[1], 'rb').read()
words = struct.unpack('<' + 'I' * (len(data) // 4), data)
out = []
for j, w in enumerate(words):
    if j % 8 == 0:
        out.append('    ')
    out.append(f'0x{w:08x}, ')
    if (j + 1) % 8 == 0:
        out.append('\n')
if not out[-1].endswith('\n'):
    out.append('\n')
sys.stdout.write(''.join(out))
" "$spv"
        echo "};"
        echo "const size_t ${name}_spv_size = ${size};"
        echo
    done
} > "$OUT_C"

echo "Wrote $OUT_C ($(wc -l < "$OUT_C") lines)"
