# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
# Pre-commit hooks for Python and Jupyter notebooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
# Ruff for Python linting and formatting
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.12
  hooks:
    # - id: ruff
    #   args: [ --fix ]
    - id: ruff-format
# Cleaning Jupyter notebooks
- repo: https://github.com/srstevenson/nb-clean
  rev: 4.0.1
  hooks:
    - id: nb-clean
      args:
        - --remove-empty-cells
