[project]
name = "pufferlib"
version = "4.0.0"
description = "Fast and sane reinforcement learning"
requires-python = ">=3.10"
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE"}
authors = [{ name = "Joseph Suarez", email = "jsuarez@puffer.ai" }]
classifiers=[
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "setuptools",
    "numpy",
    "torch>=2.9",
    "rich",
    "rich_argparse",
    "gpytorch",
    "scikit-learn",
    "wandb",
    "pybind11",
    "ruff",
]

[project.scripts]
puffer = "pufferlib.pufferl:main"

[project.urls]
Homepage = "https://puffer.ai"

[tool.setuptools.packages.find]
where = ["."]
include = ["pufferlib*"]

[build-system]
requires = ["setuptools", "wheel", "numpy", "pybind11"]
build-backend = "setuptools.build_meta"

[tool.uv]
no-build-isolation-package = ["torch"]

[tool.ruff]
line-length = 120
target-version = "py313"
include = ["pufferlib/**/*.py"]
exclude = ["constellation/*.py", "tests/*.py"]

[tool.ruff.lint]
select = [
    "F",    # Pyflakes
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "C90",  # mccabe
    "I",    # isort
    "N",    # pep8-naming
]
ignore = ["E402", "F841", "N806", "E722", "E731", "E741", "N803", "N812"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.lint.mccabe]
max-complexity = 25

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
