_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- 'f545b79ff3d553a0'
- '9c3885a3f47a5393'
- 'c2da91d86ee95141'
- '858b576bf1f25127'
- '26c3cdb68bbd50e5'
- '8cccccfd72115761'
- 'cf57e14fb0e3549f'
- '068360105b8c5337'
- '9536ab5999ce5999'
- '74f33e65028d5917'
- '436936e49747508c'
- 'd9e89ee9ac10598d'
- '44a9f55424b0549d'
- '317878d8107a57e4'
- '834cf71739e65997'
- '83daabde844e54dc'
- 'e210b8db466755c6'
- '3ecaae94fe3f5cd8'
- 'c7468120b03a56e7'
- '790824a2df935497'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
