_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '04a4a92fa9485364'
- '8118ba55e04751a7'
- '15801a1d5ec550f6'
- '84fc152d339359b8'
- '04dbabe93cdf5835'
- 'fc61fe4f440255ed'
- '87674f483b1e5419'
- 'f5a56a2c18045b2b'
- 'c11cf83340ef57cf'
- '0f2aa59c01b85796'
- '1bb4a47dd9f155cd'
- '951404943c3a522f'
- '157d4bcf09955c0f'
- '9735fbcb23e65f5e'
- 'b3f3e4c05c19502a'
- '37d66f4b3d735297'
- 'a173bab5c7b9548c'
- '8766f0a66c795245'
- '63a31921e3dd56dd'
- '0e80579390285813'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
