_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- 'd45ce3fc33ee5111'
- 'ec707117dc6655b5'
- '56f6af31e23b504b'
- '99ac1ec87510556d'
- 'f13e150be53454ad'
- '84592d9179f25c58'
- 'c2216319a8815eb9'
- 'b94178aa0e9a5f6f'
- '798e9ada32655d74'
- '11ac0cd68d2b52be'
- 'bdbec8db87c05b88'
- '992152097519529e'
- 'a6a0c2605bd15498'
- '1a9aa434305b551b'
- 'bf6ac67055945ec6'
- '322b2169ba325227'
- '28a7494f82395273'
- '5ae90b0e5dac5c9d'
- '9da92ed8992a561d'
- 'b117d99525275c5c'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
