_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '252dc073498258c7'
- 'ff251a689c125d4b'
- '0ec11905be6357bf'
- '3c7fc272a0eb5a74'
- '96e1ab46830a5abb'
- 'f56e788506ca570f'
- 'a51bd16d5f2b5a9b'
- '7e7b9ba07a3c5862'
- '88cf2d1d3b705e17'
- 'e7f998c098aa5492'
- '5edc32677b025ef2'
- '9c3754dd9d09518a'
- 'b1a7fccf043a542c'
- 'e214384948315c3c'
- '57fb4bb3faec56f2'
- '40042cb53ea15317'
- '1aa2af2ce59c5d4b'
- '9f809bb88fb7584f'
- '09387c1b42aa5288'
- '9d218f3b7cd053a3'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
