_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '8c3e010932aa5cee'
- '401700a7aa2d5afd'
- 'd6c015cfb5785305'
- '36454c3b5d685c1f'
- 'f354e32413d75c9c'
- '81dfdbd451ce5b05'
- 'fe30abef00955b4a'
- 'e990429a8ff45085'
- 'ed70a7ca5350593a'
- '2d35e82812fc59d0'
- '8fcf72fe99a4525a'
- 'a96c109c569b5904'
- '9457f00d911b5fc2'
- '470cb336d24754b4'
- 'c777d540d9d6546a'
- '4d8aa5aba1b157fc'
- 'c2bf8ba76a1d5439'
- '4ec6c6d1dd2a5704'
- 'f80c33f8b5f2519e'
- 'c63dad53040755fd'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
