_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- 'd8258821fbf4567e'
- 'df14e7a74f035385'
- 'c898e6b6f9e25220'
- '06f3e1d3f9df598a'
- '8680af9e56b05175'
- 'e6f40cb278175bd0'
- '495c616d8df45acb'
- 'da8f7d7db9065d59'
- '36bb406c02415a1f'
- '653add19767a5aaf'
- '5fa18e89e8b4562c'
- 'a9cc30d55e1b56de'
- '8bd63e2b025d5e38'
- '8bdf19ef1ae35709'
- 'c45571dbd2ce5e92'
- '04659d4c41935483'
- '631db6c25ffc54ad'
- 'd1cc883552ca57aa'
- '9ba4073c7ea05712'
- 'c9a89ec97d0a5941'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
