_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '848e7b87675454a7'
- 'edeab17e9e495644'
- 'f75ab608bc2d53c0'
- 'd600cd9504af5c8f'
- '272b44e4498c5e76'
- 'bec10cb7c4985dbe'
- 'c2f0546ea2565af3'
- 'c57a61eb33c45309'
- '5873cf0a63c65c9d'
- '5783cad294585faa'
- 'f043838992745ad4'
- '067e23d0f3495cc2'
- '56dcbd23b5c9522b'
- 'b5a8d475d9ae5925'
- '51e1743acbf05a62'
- 'dc3be40d19af525a'
- 'de124fbf80c951d3'
- '07bf12b29c385f13'
- '43ec910ac8bb5bdd'
- 'fa037e7eb0605f8c'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
