_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '6f5f540b79935ef2'
- '605d5b1c17a65f61'
- 'a9773766c9ac51b8'
- '3c6ac27e868a5039'
- '3e4742ac900d5ecf'
- '34eb025310055085'
- '4f6461c570d2541d'
- '9990c91a09335a2b'
- '5c66bdaa42cb590d'
- '0adcd0e658d359a7'
- 'f46984fbdd745dca'
- '6df4338f64cf566c'
- 'b8dc23bccf4156a0'
- 'bb3441512c405115'
- '1729f89fec425d59'
- 'b44ae5b2fd4c572f'
- '0cb3e00568cd5056'
- '8b6c460edc7e569b'
- 'fbfa092b46705d05'
- '2cfa341ef8035385'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
