_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '71550ec8a9695581'
- '828a2941f0a8540a'
- '552c8befa3c45662'
- '90e0a3e03ea6553b'
- '9795ff6460a358c5'
- '36516922212f5065'
- 'c86e8e693033576e'
- '067488f23ef3554a'
- '011d97b0e5a85f5f'
- 'b6dfb45102bf5e2f'
- 'd598deb604155067'
- '36c985d6cfeb5ba6'
- 'b48240f016ac5440'
- 'e3456b82bcf8583b'
- '4c24396165f85d8b'
- '72adcbb381bf5750'
- '8d1cc9933b715e6c'
- '8bce1db07e905f11'
- '63ef5aab300c5f09'
- 'f2cf311bbe715643'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
