_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '3dfcf6c1de425df5'
- '4eb6d1ceffdc5ef1'
- '15ad07a391fc531d'
- '219a640329bb5937'
- '029fa42dc2b050b0'
- '3bbe2bed3f6957ea'
- '76555123d9e15f53'
- 'fcc92c4f7550585c'
- '15350a341e695fc7'
- '1d827435afff5a34'
- 'ce46277ede7151f7'
- 'abdd9be326d85957'
- 'd4dab678b1f4542d'
- '137c4a602d535d1c'
- 'd9af410284a9558a'
- '5fd2c4ba12af5433'
- '2ccf908e66225542'
- 'a7be49306f3a511e'
- 'caaab29c36ef5bee'
- '4b3b50a9f58b5d79'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
