_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- 'c158bae7ba995615'
- 'ba53f4f8b3f95f9e'
- '08efd2bdb91d5b60'
- '8ebcb8a509965dc0'
- '14ceb269d7935079'
- 'ced53747c9745b55'
- '73b25588578a5b6b'
- 'a47a238ed8be578b'
- '6e357a01f9b0593e'
- '13206e5a247c5d64'
- 'bc6f3e1e87d7573f'
- 'c5314146ee805579'
- '179eadc7228f54ed'
- '8ff364cff0135509'
- 'edee67dc6b665bfb'
- '0fafd831849b59eb'
- '55b7c9f3fc3753e9'
- 'ae2d9cd51ebb58aa'
- 'f05cce67330c500f'
- 'b20af475e6f35e7b'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
