_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '42c42020703a5556'
- '4c81b08174485d4a'
- '390e7453b78a5e61'
- '49fb5285f71b5465'
- '7980ca7e5bdc5919'
- 'ed6c378bd7c15cf1'
- '75b753d130a15e0f'
- '71f20f6407c55709'
- '509c67d849bb5e2f'
- '5348275892365cdb'
- 'b567e21dec475d16'
- '28fc8dad42a25713'
- '984ee441b9cf51ea'
- 'f274e21b1d0854f8'
- '5c6c1dff8d0b5a45'
- 'e8f7ada1d5e35559'
- 'cdb5400e78d35889'
- '3b6c8de3cfa45f67'
- '95ab9a07a8f55760'
- '357617c630cc5f6c'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
