_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- 'bff510ccdeaa5f35'
- 'fc4ac353d0205b3f'
- '6e03cba240eb57b2'
- 'ae93f01c97b95e31'
- 'fd70200392e851fe'
- '0d1ff60873725367'
- 'df3209418f485407'
- 'd070c0d78c955b55'
- 'c4874465ea1f5f0d'
- 'cb1fe18bace45263'
- 'c6f813de2faa59ab'
- 'eca32130c66755c1'
- 'd145b19c2d0b541a'
- '1492e65004b65d05'
- 'bac0d1b3a1ff5389'
- 'e40809aa767b5dae'
- '9f97c852a33c5df5'
- '546748dd6dc15ce0'
- 'cedc9219a6ca5024'
- '7279496852295ca5'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
