_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- 'c3e46ff35ccd5d8e'
- '4eab926af88656af'
- '1bc4a5a636f7539a'
- '90fba04924295a4f'
- '9ff7afcfadad597e'
- 'b5e2215e09995f3c'
- '6a4b14190ead51ca'
- 'ea3ba48c466e55db'
- 'b5fab79404cb5005'
- '6537b89771ad56c6'
- '89f2e8d64ab55b4f'
- 'b9371ca8b59154c3'
- '59bb3fec07495d87'
- 'a5617ebfe1ec5b2e'
- '501e6ffbc107514b'
- '2a6fa8840c4b51f3'
- 'b2baeaa0159953d8'
- '806fefcac7255f03'
- 'c5b92860ee7a565e'
- 'c711b58fe110530d'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
