_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- 'c8ca37aa5af65553'
- '6aaaedc401ee5107'
- 'bca5ce4888c0552d'
- '57b1c8e3ba6a5768'
- '6b08669963f850e2'
- 'dbe1647a3c6f566a'
- '88b1d0e3a0f85a97'
- 'dc71315766a458aa'
- 'eb38a969ed2d5483'
- '534858c9d60955fa'
- '2103e3d9b2025301'
- '6d4ba74aba6d5722'
- '6545d57f36cb59cf'
- 'b57f7e7d71215af7'
- '5519123f7ac85d9c'
- '45da1903cbb15d8e'
- 'c7a667dbc8ff520f'
- '7a578b7981a1532c'
- '80ca832887445466'
- '3ca3041442b25293'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
