_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '318ccc0204ad5169'
- 'b2ed684a0dd1594e'
- '710f232ee6ae5933'
- 'eb93ad568896524c'
- 'bbb47a98cfa85078'
- '41a9ae95891b5a3d'
- '2847f10808615238'
- '60c31b59ab8a563e'
- '935e480ef74e5cd8'
- '73f9617c55875d0b'
- '1f463bd4f9a85923'
- 'bd2ca3e701045cf1'
- '6cc82f29edba5e42'
- '12384a61bce55dfd'
- '49e45364d9d55b37'
- '2e35d8043dfc57ac'
- '00c0d5bcf6d55c23'
- 'd76bf6cad6775ab9'
- '5b3fa11325e95c68'
- '1001304290285954'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
