_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '747d04c2b4c2503b'
- 'c455ca6714a5529d'
- 'bdbe2ae115145f05'
- '53348cde5f3e59e4'
- '4930fdc43c1857ae'
- 'f0c58378b81d55c6'
- 'f9ebab3c21c35d4d'
- 'c32797bd505b5dd6'
- 'ad416b6d102b5397'
- '6bf2ff95192d5cfb'
- 'd57e14582102599d'
- '601c7bce7ecc5b46'
- '5fdf486d23b65b07'
- 'ce9a8994426651f9'
- 'd11127b28e035c06'
- '3639112fbe5354b8'
- '00c202ab992e50aa'
- 'db04a329549850c7'
- 'f9d4b59f3a13590d'
- 'bc9cc5644a0454b0'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
