_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- 'c3c3362c0698581b'
- '3b21090dafc054b9'
- '0fef035e25f455fc'
- '0d306053f89552cc'
- 'a63404b6ee7a5ca4'
- 'ff9f884349e65234'
- '531dcee0f8755393'
- 'ae3f307de8615b35'
- '1aef09b936ca5f72'
- 'cd73b30d7cfb5ed7'
- 'c8281e1e1ad454b3'
- 'dc3fb93cdf8c5a6d'
- 'c2a9cec54e935adc'
- '297460a38cf85c4a'
- 'f07146d3d0f85bc5'
- 'cf1b27fc3ed658b2'
- 'd77157608aad5340'
- 'b7ec5cdee9765f23'
- 'c56297c6cebd57b4'
- 'e078f1cf064f5580'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
