_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '847d404274f45a31'
- '5279e16c735e589e'
- '75900dd01f025b22'
- '6b833c4f6ba85107'
- 'dadb50dd16e7550f'
- '2609befadf81533d'
- '960022bf017958a2'
- 'f3c5008618555385'
- '0a460b8b55f15728'
- '3cede85b3ad15871'
- '43684e638e545af7'
- 'a264f3c05f175e4c'
- 'd9fd1bec7465502d'
- '8d0a9c0e890c5ec8'
- '23c15f974b725070'
- 'b145ce43a53b5d7b'
- 'e7f119f370385c70'
- 'f7b8320599e7561d'
- 'bbc7bb010c275ea4'
- '2b5f330cc84a58d3'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
