_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '5343ee1857dc5c82'
- 'a997150843765f15'
- 'ae126678b4a65269'
- '2b2650c2d1835ad4'
- '4bb4892d273356d0'
- '88eb75d4ebc856d3'
- 'f2b91abb2682592a'
- 'ae68d243a14a5e73'
- '6744a91db9485d20'
- '5c368994f4f2586c'
- '26f9ee1ca73e5e0a'
- '1f82b16afa96569a'
- '3bdf055c00125477'
- 'cac80a08729355f1'
- 'efc954a351a350f2'
- '71a1225cd14a53c0'
- '6c9d5706ae415e2a'
- 'ff87f53ee3b85930'
- '9434766d819c5239'
- 'bf314c96e26159dd'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
