_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- 'e1ee5cc0316a5b9d'
- 'b1034855ca2b526f'
- '2508702d9964588a'
- '390b7a4290705fad'
- '288df93a91a25d2a'
- 'a7efeb87f0965e06'
- 'd0a4453b79835179'
- '2de25261077153ef'
- '00301fbca75b5ce4'
- 'efe98217d366577c'
- '4064de4004385810'
- 'cb18c15a8d615d95'
- '78b39c7e52c85ad5'
- 'c09e079e5f675e68'
- 'afc40829c4c151e6'
- 'f247363c6a895c18'
- '834d5f5b024d5b4f'
- '03ef717aff06535f'
- '1b9234d32b0750bb'
- '018efa6cfcf05b38'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
