_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '900d088d9c815aac'
- 'd8d3da1a03be535c'
- 'f6bcde0e79bf5f7a'
- '6f247bc70fe3555e'
- '23cb24f7bfb95e52'
- '6badb2820fd251fd'
- '363a2433837659dd'
- '55f10643a7c55642'
- '0e3ebea8bc015a83'
- 'b3b660d07d0453cd'
- '26a70fbb0bc6522e'
- '2315ca6fdcf65ce0'
- '5598103d55ca5cc2'
- '9ba46464c5d05ba4'
- '3f21b22dddb650f2'
- 'cd6bb9145f305d6f'
- '010daf87039b5ac6'
- '96a626b4962a5b79'
- 'b7e5b7dc41d95bf4'
- '2ba56b194be35170'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
