_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '1fc135287cce5f74'
- 'fb12a40e998254c0'
- 'd1233a44bda8587d'
- '53a7722e3f4e5402'
- '5367c39160105a92'
- '4e5f5d37a7f55d50'
- 'ffaf0595e6b15a1d'
- '0b709d67a7b457e3'
- '157675dfe46d564b'
- '0b0e4ef7390c5e32'
- 'e76c2e115079581b'
- '29cfa239ca925107'
- '517c68cd7fc95829'
- '7bf0e3c467765904'
- '8d3c4c8456485f02'
- '59ea7796d6bb5870'
- '5ff50502a8025ec4'
- '921506147e78501a'
- '6c1c0eee57f15149'
- 'cea6d0cc7fae5b64'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
