_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '8b4daccc76555c6c'
- '2ddf1d019e4b560e'
- '54638dab1a8d5cd0'
- '7762454067955400'
- '4e84e89c03a057f4'
- '71b3a829aa955429'
- '9be7b4ef51ad537b'
- '558d1c44968c5319'
- '4196301b207f5f09'
- 'c8a6f99ae43750a9'
- 'fee0a0e2c7f35b57'
- '174934676f935862'
- '15416947b62a540e'
- 'a7d5055f7958550f'
- '5e0cf44e7e735acb'
- 'c7dfc26b80d15e37'
- 'cbff64d4a3275eb2'
- '0dc096721b925852'
- 'b20f8849949a5781'
- '494fe3ac4ae75c8f'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
