_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- 'd02abcb2b018515d'
- 'bd4a927480be5f40'
- '30195f6787f757e5'
- '13eeb0a3d27454cd'
- '830d852b4d125dd8'
- '69aa212a73e658a9'
- '4605086c40815117'
- '176dbea202c85b1d'
- 'c9464a3eeb595732'
- '2f9fa2092bf05a7b'
- '4769a4aa80eb5bfe'
- '4dd6951ee5975dab'
- '04f7fbf12de65cbb'
- '518293c438b45717'
- 'a81d831747125494'
- '15320d9700e152e2'
- '7f52eb0df56b536d'
- '52a6fc6e93945378'
- '18438b7efd275e7a'
- 'c0f43985dd8c5a6f'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
