_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- 'f013b7d5cc4b5640'
- '94486171a0d0586a'
- '504019ae3310580a'
- '82eda340c3ff5f37'
- '3cb0bc35d9b3568c'
- 'fc95574ebac8588b'
- '1f92b9e3409f52bd'
- '83a18a11bf9b5baa'
- '33d291fdc9ec5f29'
- '618aad445b8d56ed'
- '16b29545f7355276'
- '6be690074b835ee7'
- '574ba611316451c3'
- 'e42b7a4f6bef538a'
- 'fed1da9b14af5392'
- 'b9aa20bc06315153'
- '11deb182a82952e3'
- '806df3c0ed23596f'
- '081cc4dd40c559cc'
- 'd3e4d463eec25d67'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
