_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- 'f958ec121f5a5287'
- 'b9ab639fd02f5199'
- 'ae5eff08c15f5772'
- '383b3d0dc4b955bf'
- 'bc62496a861c5c6c'
- '6980261fb6c5566c'
- '550be0ceaa375286'
- 'a7b19f865b7c5786'
- '392f65dbbb4c5b3f'
- '30bd4a80c1f45c5d'
- '7bd2275c5d3d53df'
- '5e8c626551b15567'
- 'b9231de6bd845d76'
- 'e32452537a3d559c'
- '1d5b9b166f0c5912'
- 'a755cd5ec46b5153'
- 'd7d8bec6f4055a6b'
- 'f2775866549b5580'
- '02be5baf00be511e'
- 'ddd2c4e69fa159a8'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
