_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '30e0f8ea46375f52'
- '8081e335d96056e0'
- '73bf19dc6384554c'
- 'efe0e8c737105303'
- 'cb8c00bd27ef5407'
- '71723288646957b2'
- 'dbbd1fdecb775d9d'
- '605598ad9db955c1'
- 'e5030ab7fbc65617'
- '9b74d8ff8b6a56bf'
- '6a389d45c87e5bd5'
- 'e72fb7eca4b857a6'
- 'fa20c34947a8558d'
- 'f397d4d6ceb650cf'
- '5ee51ad4d9345048'
- 'cd63e5191fb854c4'
- '2aff210d87d25cf5'
- 'f1ee9c9a46045dd7'
- '20dd31cd90325acc'
- 'c31f7d6bb4735d2b'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
