_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '0cf9756ece935921'
- 'c1567e02a98e53e5'
- '6bd8a2debd375328'
- '05b9e0a5a3055aa2'
- 'a6177e5e80515a6f'
- '0b23f003881e5a2f'
- 'e52a507151b45124'
- 'a3aca140c0bf5735'
- '014633279fde5c6b'
- '133baa14fb5457ac'
- '0cd0bb95c83751e2'
- '391243623ee2507d'
- '26cd2c1bfff85b53'
- '9a190b59608a5715'
- '7c0e256904125fa8'
- '61b67d5ab3da50e0'
- '79765415cff753ec'
- '1898ebe818eb5b39'
- 'c6b3b3d1d9fd5bb3'
- '39828cebcafe5966'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
