_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '42dc17b3a3e551bc'
- 'bd164fe385355150'
- '1093c17783b1551a'
- '05f5fd6850305b2a'
- '82317508dea55b9d'
- '43dc01b7f36c560b'
- 'f97fb70da693571a'
- 'd4832fbb31ef591d'
- '8e9c515ace025bfc'
- '1b4b10506d6e589a'
- 'f36c397ff1125e10'
- '341f2720ef215146'
- 'fd7082e9536f564d'
- '428a595895755ca9'
- 'f02ab3bebb3e5532'
- '8ac5e0919877529a'
- '617eb54159435481'
- 'a27cf7fded2e5a3e'
- '6c29ab9f10c852e6'
- '77d818bb3b8e5ddf'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
