_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- 'f1f8af6bf7685fa3'
- '5d070fa13ed956b0'
- 'b3e8728bd5ce5340'
- 'cc1488bdd3415eaa'
- '9632ec0169755615'
- '6786d11321ff5a38'
- '2e372e016da350ad'
- '6c3c40f8dd8e5f5e'
- 'f4342f3a92e75b7d'
- '47e88f1126075d8c'
- 'a1f7bd32669f583f'
- '8ce9083add14517c'
- '4153b8d26d995fee'
- '3dc3d20b2f78573c'
- '222e748894675f29'
- 'e504f54a41665d9a'
- '4d05cdacbc7e5078'
- '119ac9e47adb539c'
- 'a22d7a6a37a85b74'
- '8cc6163baa165a70'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
