_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '5424b93732bb5842'
- 'a684abdd377a5526'
- 'c556f4bc6f165a76'
- '57534af9046058a2'
- 'af1ff1ba8bfa51ee'
- '15990b4dfd035da3'
- 'ea34b66a5b9052e3'
- 'f56a86ca7c8459ba'
- 'aa729da77b7a5900'
- 'f1c0b066cfca5c81'
- '626f33408a435f47'
- 'c80486444a075315'
- '74756890e549577f'
- '3ad61242db035638'
- '8eb8410b1e385101'
- '765479ca832950f0'
- '3c3e8ef4ff185bb3'
- '71d9e22cea3f5469'
- 'c4b7f40d72ec5860'
- 'e70f19d46048540a'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
