_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '7d24fb93bcf850e8'
- '5e401393da265fab'
- 'f79fba8bf0265552'
- 'f6de0b6ee41b56b0'
- 'e2f3f2a226bf5570'
- 'a66548684abd5654'
- '680e1ce48b255213'
- 'fcaf1d68979d560a'
- '2676de7a1f395982'
- '1c7d81d771715ba6'
- 'e59d7ba3a5c1500b'
- 'b70085dba0765845'
- '498d29a688f25631'
- '1a61f929adf95542'
- 'b09528b71a5451cf'
- 'eac481b592f35bbc'
- 'ef5afdcb26a95f07'
- '0217d32c99f35e8d'
- 'f769cbb43790525c'
- '3ef425a63b515bdb'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
