_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '2f8b6f87b2265b65'
- '72c4b3e9788b5bf7'
- '3069f8795e1c5116'
- '362648401371516f'
- 'f3aa2dce8d605800'
- '77b6537477045172'
- '30aa28efb1a45959'
- '9dde07ed9e5455d3'
- '903bef71f2ef5465'
- 'b662f7a2aff650bb'
- 'b776d43d2e295eb2'
- '23618ef975b35da4'
- '18c2c17b55e956a5'
- 'a59dcad188095204'
- 'a50c3f22fcf65ebb'
- '392b41b3af975424'
- '8454b2b637175956'
- 'b4199a4f019e5984'
- '049dada6c5635d20'
- '317ff9c87dfb50ae'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
