_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '3e3d32dde22256f2'
- '99ed7cf98b365d63'
- 'ea21832979875423'
- 'e8fd7512fe6b5486'
- 'e12e5fc62aaa53bd'
- '2e3a20d7f8015043'
- '53f040fc7b815331'
- '457238fe173052e9'
- '242b3d8fc7df5fc7'
- '4618e83e82d851db'
- '93455e89334950b2'
- 'ece5db3b69b25403'
- 'dc6ad473cea05799'
- 'af819d19bc8a5e93'
- '4a1cedb052d35575'
- '6ba25ebff18154fc'
- '37a0dd129f335fb5'
- '818da44b164e5abe'
- 'e6c0fbf6b7d95fa4'
- '011a76cbdda851bb'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
