_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '0bd3ee0c8e1357b2'
- '23367af0cb705f70'
- '3196c324c82c553c'
- 'f9c453610b045457'
- '4850ef64e2c255d4'
- 'ad6d872bf6995001'
- '6734f71cf94850bb'
- '8a5fb3de4e785f87'
- '35af99c29b41575b'
- 'c47d40dd4aa95b21'
- '2aee1cbe8420561b'
- '5badc98899c35e10'
- 'c0f1326b41465187'
- 'cc1692bc3a625b0d'
- '7e4d2e8aba825cdd'
- '9ea5d395e1655fe5'
- '756942237cdf5a95'
- '42eabc4389605381'
- '993b14add9b3537a'
- '005d90072df15dca'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
