_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '73c65f8cfa0b5f49'
- 'fc4760dc057c5aca'
- '2965e4c9734152d9'
- '0e1e0ca3678759e0'
- 'd20cdd25bddd593f'
- 'd19f6cd9a32d5eb9'
- 'e57de37711215456'
- 'b43bd580ef6d5873'
- 'e93d10f1942956a1'
- '90c1f6c5e89352be'
- '0942e763807c536b'
- 'bd9267c026a85b24'
- '8a8d68f7b91556fd'
- 'b26e0f55c6635cfe'
- '7293e44c51595f9a'
- '9731e046e0425cdc'
- 'c3afbe8d5dfc5ec7'
- '4062618aa1345db6'
- '443bc5caadc05ea3'
- '5e22eb66e795588d'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
