_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- 'a68eddd8d64c5748'
- '9d15a6330fb0542b'
- '2e3bc88b97d9591f'
- '370e453a4f6e55cf'
- '2afa35fd7baa53e0'
- '6d34396ecc375932'
- '8fc3f9bd06a25423'
- '471fd96fa4e85e00'
- '022fcc82f6d55f46'
- 'c74354e114e25a5e'
- '5f126e11a529558a'
- '40d3dea94d5a5df7'
- '773dd0a156a25f05'
- '96424a88a5e5592b'
- '7fdfe78ce40851c8'
- '5c0d5992039c5ae5'
- 'c31e875e21ba5ef3'
- 'd2ad32d40e255c03'
- 'f54dded0dc4d52fe'
- 'bdb0af2d9e105721'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
