_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '19d86eeed8aa5034'
- 'c2c21ab3a46e5fa3'
- 'ad5cd8212eb05b13'
- 'e268e0ae47f25794'
- '2ae1a98a4abb5634'
- '50e522bacee65947'
- '59fb65ed6b6a516b'
- '62f1226f09135822'
- '2b1bf6fda6a35e0f'
- '91ed1256a8515b8a'
- '9af3c5d9eadb562a'
- '501383db138758ce'
- 'ffbd3b860a825ef9'
- '6b5577c4ad065b64'
- 'c1e1aa49ca6d5f5b'
- 'b3b0248521b35ad9'
- 'd380e90d6bf75fcb'
- '717f8156c219581c'
- '2a1ee001593a5b12'
- '9a0e3116d3f95fb0'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
