_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '691bc6f41d6456ea'
- 'e8929dd8178a595f'
- 'd2d0152ca8b45448'
- 'b1f369f514d95f4c'
- '2a9eaeaef4d2579a'
- 'f51fa581f64b5b3e'
- '2c6685877c5c5add'
- '35c34962ceb55ae1'
- '3b882e9cddd75b23'
- '0317b5f6ca155438'
- '8aa5b35af763528f'
- '90378791899c5f0b'
- 'aa3bce96f7795abb'
- 'bb316a29dda4579e'
- '48303bdf88815d47'
- '7842f544a27154be'
- 'f84f9906ecaa564c'
- 'a750010a71535826'
- '9d37c0d42e6e5db0'
- 'f4d5adfe95c5518c'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
