_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- 'dc09c00279cd54a7'
- '3c1bdfaa9c0f5351'
- 'e9b30fc73b785460'
- 'efd37715c9165bee'
- '81e4805c11bb57ac'
- '9e345f0a2740505e'
- 'c784279daa025ecd'
- '771297a09a50590e'
- 'ecdd80b34a8f57a1'
- '131e121d08bc5b5d'
- '8ade6f0fdead5bbe'
- 'f5f241207ac8528c'
- 'f199f564fa885384'
- '4665f922e9f658df'
- 'aa0c80c9004e53e0'
- '8c571a72ea545228'
- '5055371cab9c5a76'
- '68e0ff1df2b6587c'
- '89f3b2c5f2755984'
- '68de727e3e2b53d2'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
