_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '4ce8319955305a2a'
- '0e97991aaf6858ae'
- '8664b363dbe6579c'
- '005c7b67ab8c5eb7'
- 'bc552fcf837c597e'
- 'b0ab4efe7be45584'
- '90489718be785427'
- '7426524f502552e0'
- '16966427ad615141'
- 'ef50b86138685a7f'
- 'ca910aba9f01522a'
- 'dfe09b52c98a5d55'
- '49503ce0e8f25ea7'
- 'ed66148010795fd5'
- 'f1595418c3325a9a'
- '2acb1cd62bbc5f5d'
- 'd4c8c61f071c5f51'
- '99822c6ea67c5cb2'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
