_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '2d4fa9eb37155845'
- 'edc52e8bb5a75de0'
- '795a5057ce3c5fdb'
- 'a657d9c0c5ac5d86'
- '0ef51935e41853ac'
- '4ed00530dda15620'
- '76c046586ec65d90'
- '0c6560fdf22051d5'
- '271aa6aadc005dec'
- 'ceade829ae42587d'
- 'c0a9f2a2cfd357c5'
- 'a64188586ebc5d4b'
- 'efddae2657e95e70'
- '8129ef38aa0c5416'
- '50de55c64b3a5cec'
- 'eb1ac330d8bc5a34'
- '236f917924b6546a'
- 'e410e8eb7ebe5cba'
- '4274e203840a5744'
- '7c59b23242215b68'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
