_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '0d692e23ea0954fa'
- '22fbae96f7bb57e7'
- '587d629b0b535e68'
- 'be7706a2289957c8'
- '3c2dc4fa5cea5da2'
- 'e3e2933994835eba'
- 'c39fc085da325b58'
- '7ab2527d43b55c00'
- 'b7a0f107522e5c85'
- 'f6cc37b600355f8d'
- 'fb110f8fa95d578b'
- '45a064795bcd5136'
- '882b5af1243757f1'
- 'b61c04639f435416'
- '4162062bae725fec'
- '722bbd202c835db2'
- '15455c755f3d5f8e'
- 'b4e45738e3f85601'
- 'e214555df62554bd'
- 'f84836b6b3b75e15'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
