_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '0338779ea8ba5128'
- '05f93c480c1d5984'
- '8fc9474f19a35ab8'
- '3e0286a995c15ac3'
- '10d85fb5f17452dd'
- '407052775bd75ef0'
- 'c5b585c0103c5340'
- 'a486bb1feda5577f'
- '7e8525c900f15ec4'
- 'f303c375c15055f9'
- '6e4234134bad5f11'
- 'fe98ea92e56f5f91'
- 'ced3856a5bee5575'
- '27ac70975fc05636'
- '5285285e44415f24'
- 'e8997fd743685ce6'
- '3c52b858ed005198'
- '317d093b6b4f5485'
- 'f779e983fea75d2c'
- 'eaadad7dbcf05511'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
