_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '52e379ab3196503b'
- '5ce3e28be5b455c4'
- '2ede0b68d4f05726'
- 'a723915521ec5f4f'
- '2dedd41ee75d52ff'
- '6bd725d8fb4e569f'
- 'b68dadebc7d550c1'
- 'ff3e4f2876045591'
- '346f60e6d90b59bd'
- '89a6f0ca56e15d44'
- '181412fd9fc453bd'
- '2a85528ed1735741'
- '0ebba0e8fbd3528f'
- 'aab588ad361a5274'
- 'd5fb322ec0b758d3'
- 'fa82f3a838b15805'
- 'e34c9ed042405fe4'
- 'b10cf48b6a62535f'
- '8c3efbd29dac55de'
- '0ba3bc329f625a87'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
