_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '2758a26de2eb5687'
- 'e03138d48b2350a1'
- '0617d2b7c3c956e0'
- '05abec5c2a67537b'
- 'cd5f0c03103359b4'
- '0be4b33676df518b'
- 'f3addd50ef9b52ce'
- '6e25d4267f1f56cc'
- '9335a6ee8bcc5464'
- 'c30b795fb1025200'
- '52c0a201a18a5117'
- '34abdafdc5bf5f02'
- '29b2a32bfd73543e'
- '3260e05e584d5fe8'
- '4629b70d7cca561b'
- '6e572a3a5268572b'
- '0b0264ea387a59eb'
- '8cf8fdc6335a5afe'
- 'f64e88b392855abd'
- '0ad8665aace75ef7'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
