_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- 'e04d9ab64a0854f3'
- '6ad66438155851ee'
- '760f8c7570d455a1'
- '870683ea3c405397'
- 'f45001858b8e5422'
- 'eecc1b44bd025ffe'
- '80767ab1136e5ef1'
- 'ef4ea04e79b75daf'
- 'be122bb68faf5101'
- '48091c891390551f'
- '224a49a1ad4d5ed3'
- '33217f8386bb51fb'
- '7f16af19af0f555c'
- '6a8c3640f2b550a3'
- 'f9cdf3dd4bcd54d8'
- 'f00857cf14b15aa5'
- '31c1db5f5a285e31'
- '3904a28507e05231'
- 'c8b3b870b8f352cf'
- 'ac83bb7914fa5c49'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
