_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '720c398c8755532f'
- '92cebf9e9bee5055'
- 'a1c2c3c522b7573b'
- '0f218605b46855a3'
- '77f1933d7eea5dad'
- 'c89b3a61af8954e9'
- '8b526b8ae68f5848'
- '314c40db095d5cf6'
- 'efdc9b3c63b4521d'
- 'cd94f6071141524f'
- '7736cf1972215f9a'
- '1f8b1a546a215f1d'
- 'e006d5e1b2ea5da8'
- 'b1d79dfb7cec5cbd'
- '1863deb853a051b6'
- 'a926cdaab7b05fd3'
- 'e8a0328d71c95c9e'
- '9387290766565a6d'
- 'c1181b16da455fb9'
- '72f00754294d52f5'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
