_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '875d9d5903385c85'
- '9734366e17375822'
- '1c06e56cf14a5066'
- '53ebedd520395ec4'
- '6e6ad7c8e2d95123'
- '524c76c5d0d3578a'
- '4f35bf5851185447'
- '150f990d11255003'
- 'b4fea136b474504e'
- '56b6c828cee7571d'
- '477012ad90bd5ead'
- '046372b7fe3253ee'
- '8ad4fbbaa4e35772'
- 'cf0f121bdeed51f1'
- '0c87850fe06e516c'
- '45f20433b45a554c'
- 'f216b1453e5352e4'
- '1c83f8728505588c'
- 'ab2e7df4a2645804'
- 'fbf76317822452b3'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
