_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '1a66a7c3545d5323'
- 'd506fe99e97c5950'
- '9553e5e5324655c9'
- 'e15f7fb227925f87'
- '9e63f0fb486955cd'
- 'ed8c0ae24032517e'
- '7f8f161607df5291'
- '1d6eacd8e7425dcc'
- '6c089515e0a35c87'
- 'ef4fd9e246ca563f'
- '45ad3eeb549056e1'
- 'f7a3e8c94a4d5d22'
- 'c0a520c971775b7e'
- '5a5f644a927b5d42'
- '3b8ed6209db55bce'
- '8c29bbd3294a5a6e'
- '738efdf625b35ff9'
- 'b01531a0a9da5ec3'
- '02a982b22eed53fc'
- 'aba6e59e9c3f5e65'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
