_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- 'dce0f77630e05c67'
- '33a911fcc99150b1'
- '1efdeee099b2567b'
- '89bb5d1470dc5707'
- 'a00cdefa24dc566f'
- 'aa70fa6e14c551a5'
- '08388d303eda596b'
- 'fa29b55eb9bd524f'
- 'e0b356c707fa5cd8'
- '4146a5366b6c5248'
- '7b7128c02637583e'
- '14f14589432c5e00'
- '0145ec6231b65c05'
- '1e77a04e93c75ba5'
- '220dc5aa304859b0'
- '3573dd679e045c58'
- 'fd58ebc254395f3c'
- '6591919b5db45646'
- '0777c61d992a5c04'
- 'e2c9d4f7a6ca5df7'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
