_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '24574a3fa2ed576e'
- 'dec1c86d9a2e501e'
- '79766599ff6b5b62'
- '377263dd49b6523f'
- '0a05b5cb5f6454b0'
- 'b1fbc08053ee5840'
- '67e15557b1205ca1'
- '1e5876a1d8045e46'
- 'b031b845dcd751fd'
- 'ee9885ffc5195695'
- '5bcaaed9e73f5fc2'
- 'b771a8b79cc45834'
- 'f12b46915ede5842'
- 'b2ab7d150c1f5fa4'
- 'be26059ef668586e'
- '53e9d4fd576f5955'
- 'fb7742eb940853b5'
- '0e230c7c31ee5638'
- 'e56e50ab80aa5e49'
- '88b59b17628a52a5'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
