_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '5e9f495673d85c0a'
- 'cde6323828d75043'
- '5623ca9a4b3d5764'
- '6e6b7deeec9151a4'
- '82d44a9b699e5a87'
- '4162c249e17358ff'
- 'bf6ed5c0c14c5095'
- '5b9caa65cca55c3f'
- 'f18b5cfbf3ac5e77'
- '69038042d9085f7e'
- '1d68dfeb693b526b'
- '5d91ff45ef9d568f'
- 'd651f6468ef752e1'
- 'd7dce1fd382b5ae4'
- 'fd3bfa7e0a3858cd'
- '2cdde2c236085d4d'
- 'fa19fe7ce29b5b2c'
- 'f7f0989080295b75'
- 'fdab64bdd0b2522a'
- '04c0e32756d351e2'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
