_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: all
scenario_types:
- starting_left_turn
- starting_right_turn
- starting_straight_traffic_light_intersection_traversal
- stopping_with_lead
- high_lateral_acceleration
- high_magnitude_speed
- low_magnitude_speed
- traversing_pickup_dropoff
- waiting_for_pedestrian_to_cross
- behind_long_vehicle
- stationary_in_traffic
- near_multiple_vehicles
- changing_lane
- following_lane_with_lead
scenario_tokens:
- '35b63e40217856e4'
- '29be0c5292695bb7'
- '72d1ff8ce9d65996'
- 'ed9770b157c75a90'
- 'b8ae3eb400ba5752'
- 'b7ec3b2902655a05'
- 'f47d8b7828245583'
- '8982572605425112'
- 'c766017cb6c6548c'
- 'eb2a371993b15a06'
- 'bf58490d6df954c9'
- '2f88c85f16a6567f'
- '60111f56cdd658d8'
- '81f2464a004e54d0'
- '8b5c8db732be5c8d'
- '60c1bc7de8ee5b8a'
- '2d974e401de45640'
- '996fc24078565ed4'
- '2ee2a0bbeef25e75'
- '5cf015df04bf592f'
log_names: null
map_names: null
num_scenarios_per_type: null
limit_total_scenarios: null
timestamp_threshold_s: null
ego_displacement_minimum_m: null
expand_scenarios: false
remove_invalid_goals: true
shuffle: true
