// Generated by scripts/extract_carla_vehicle_dims.py from CARLA 0.9.15. Do not edit.
// Fields: blueprint id, length_m, width_m, height_m, wheelbase_m
typedef struct CarlaVehicleDims {
    const char *blueprint_id;
    float length_m;
    float width_m;
    float height_m;
    float wheelbase_m;
} CarlaVehicleDims;

static const CarlaVehicleDims CARLA_VEHICLE_DIMS[] = {
    {"vehicle.bmw.grandtourer", 4.611f, 2.242f, 1.667f, 2.935f},
    {"vehicle.mini.cooper_s", 3.806f, 1.970f, 1.475f, 2.511f},
    {"vehicle.bh.crossbike", 1.509f, 0.866f, 1.612f, 0.956f},
    {"vehicle.diamondback.century", 1.656f, 0.582f, 1.620f, 0.960f},
    {"vehicle.gazelle.omafiets", 1.843f, 0.659f, 1.776f, 1.127f},
    {"vehicle.audi.a2", 3.705f, 1.789f, 1.549f, 2.506f},
    {"vehicle.audi.etron", 4.856f, 2.033f, 1.649f, 2.900f},
    {"vehicle.audi.tt", 4.181f, 1.994f, 1.385f, 2.642f},
    {"vehicle.chevrolet.impala", 5.357f, 2.033f, 1.411f, 2.982f},
    {"vehicle.citroen.c3", 3.988f, 1.851f, 1.617f, 2.684f},
    {"vehicle.dodge.charger_2020", 5.008f, 1.882f, 1.535f, 3.044f},
    {"vehicle.dodge.charger_police", 4.974f, 2.038f, 1.542f, 2.992f},
    {"vehicle.dodge.charger_police_2020", 5.238f, 1.930f, 1.638f, 3.044f},
    {"vehicle.ford.crown", 5.366f, 1.801f, 1.575f, 2.916f},
    {"vehicle.ford.mustang", 4.718f, 1.895f, 1.301f, 2.886f},
    {"vehicle.jeep.wrangler_rubicon", 3.866f, 1.905f, 1.878f, 2.308f},
    {"vehicle.lincoln.mkz_2017", 4.902f, 2.128f, 1.511f, 2.871f},
    {"vehicle.lincoln.mkz_2020", 4.892f, 1.837f, 1.490f, 2.860f},
    {"vehicle.mercedes.coupe", 5.027f, 2.152f, 1.651f, 3.289f},
    {"vehicle.mercedes.coupe_2020", 4.674f, 1.812f, 1.442f, 2.833f},
    {"vehicle.micro.microlino", 2.207f, 1.481f, 1.376f, 1.525f},
    {"vehicle.mini.cooper_s_2021", 4.553f, 2.097f, 1.767f, 3.010f},
    {"vehicle.nissan.micra", 3.633f, 1.845f, 1.501f, 2.490f},
    {"vehicle.nissan.patrol", 4.605f, 1.932f, 1.855f, 2.839f},
    {"vehicle.nissan.patrol_2021", 5.566f, 2.150f, 2.045f, 3.279f},
    {"vehicle.seat.leon", 4.193f, 1.816f, 1.474f, 2.736f},
    {"vehicle.tesla.model3", 4.792f, 2.163f, 1.488f, 3.005f},
    {"vehicle.toyota.prius", 4.514f, 2.007f, 1.525f, 2.819f},
    {"vehicle.harley-davidson.low_rider", 2.350f, 0.766f, 1.649f, 1.620f},
    {"vehicle.kawasaki.ninja", 2.044f, 0.797f, 1.523f, 1.386f},
    {"vehicle.vespa.zx125", 1.817f, 0.866f, 1.590f, 1.309f},
    {"vehicle.yamaha.yzf", 2.191f, 0.866f, 1.530f, 1.549f},
    {"vehicle.carlamotors.carlacola", 5.204f, 2.627f, 2.467f, 2.665f},
    {"vehicle.carlamotors.european_hgv", 7.936f, 2.891f, 3.462f, 4.411f},
    {"vehicle.carlamotors.firetruck", 8.468f, 2.891f, 3.827f, 4.995f},
    {"vehicle.tesla.cybertruck", 6.274f, 2.390f, 2.098f, 4.075f},
    {"vehicle.ford.ambulance", 6.366f, 2.351f, 2.431f, 3.770f},
    {"vehicle.mercedes.sprinter", 5.915f, 1.988f, 2.561f, 3.662f},
    {"vehicle.volkswagen.t2", 4.480f, 2.069f, 2.038f, 2.444f},
    {"vehicle.volkswagen.t2_2021", 4.442f, 1.775f, 1.987f, 2.544f},
};

#define CARLA_VEHICLE_DIMS_COUNT 40
