[base]
package = ocean
env_name = puffer_drive
policy_name = Drive
rnn_name = Recurrent

[vec]
num_workers = 8
num_envs = 8
batch_size = 2
; backend = Serial

[policy]
input_size = 64
hidden_size = 512

[rnn]
input_size = 512
hidden_size = 512

[env]
; Options: "gigaflow", "replay"
simulation_mode = "gigaflow"
; Reward conditioning
reward_conditioning = True
; Reward randomization
reward_randomization = True
; Total number of agents in the environment
num_agents = 1024
; GIGAFLOW-specific: minimum number of agents per environment
min_agents_per_env = 10
; GIGAFLOW-specific: maximum number of agents per environment
max_agents_per_env = 80
; Actions type - options: "discrete", "continuous"
action_type = "discrete"
; Dynamics model - options: "classic", "jerk"
dynamics_model = "jerk"
; Time delta between steps in seconds
dt = 0.1
; Behavior when agent reaches goal - options: 0 - Respawn at new goal, 1 - Generate new goal
reach_goal_behavior = 1
; Target representation - options: "static", "dynamic"
target_type = "static"
; Collision behavior - options: 0 - Ignore, 1 - Stop, 2 - Remove
collision_behavior = 1
; Offroad behavior - options: 0 - Ignore, 1 - Stop, 2 - Remove
offroad_behavior = 1
; Traffic light behavior - options: 0 - Ignore, 1 - Stop, 2 - Remove
traffic_light_behavior = 0
; End SDC path behavior - options: 0 - Ignore, 1 - Stop, 2 - Remove
end_sdc_path_behavior = 0
; Reward coefficients
reward_vehicle_collision = -3.0
reward_offroad_collision = -3.0
reward_traffic_light_violation = -0.0
reward_ade = 0.0
reward_goal = 1.0
reward_goal_post_respawn = 0.0
reward_overspeed = -0.05
reward_comfort = -0.05
reward_velocity = 0.0025
reward_lane_align = 0.025
reward_lane_center = -0.0038
reward_timestep = -0.000025
reward_reverse = -0.005
; Meters around goal to be considered "reached"
goal_radius = 2.0
; Number of target waypoints for goal representation
num_target_waypoints = 3
; Goal waypoint spacing range in meters
min_goal_spacing = 20.0
max_goal_spacing = 60.0
; Number of steps before reset
scenario_length = 128
; Frequency of resampling scenario (in steps), 0 to disable
resample_frequency = 0
; End of episode - options: 0 - scenario_length, 1 - early reset when too many agents are removed
termination_mode = 1
; Path to map used for training
map_dir = "pufferlib/resources/drive/binaries/carla"
; Number of maps to load from map_dir
num_maps = 1
; Determines which step of the trajectory to initialize the agents at upon reset
init_steps = 0
; options: "control_vehicles", "control_agents", "control_tracks_to_predict", "control_sdc_only"
control_mode = "control_vehicles"
; Options: "created_all_valid", "create_only_controlled"
init_mode = "create_all_valid"

[train]
total_timesteps = 10_000_000_000
anneal_lr = True
; Needs to be: num_agents * num_workers * BPTT horizon
batch_size = auto
minibatch_size = 4096
max_minibatch_size = 4096
bptt_horizon = 64
adam_beta1 = 0.9
adam_beta2 = 0.999
adam_eps = 1e-8
clip_coef = 0.2
ent_coef = 0.001
gae_lambda = 0.95
gamma = 0.98
learning_rate = 0.0005
max_grad_norm = 1
prio_alpha = 0.8499999999999999
prio_beta0 = 0.8499999999999999
update_epochs = 1
vf_clip_coef = 0.1999999999999999
vf_coef = 2
vtrace_c_clip = 1
vtrace_rho_clip = 1
checkpoint_interval = 20
log_interval = 10
; Rendering options
render = False
render_interval = 1000
; If True, show exactly what the agent sees in agent observation
obs_only = True
; Show grid lines
show_grid = False
; Draws lines from ego agent observed ORUs and road elements to show detection range
show_lasers = False
; Display human xy logs in the background
show_human_logs = True
; Options: List[str to path], str to path (e.g., "resources/drive/training/binaries/map_001.bin"), None
render_map = none

[eval]
eval_interval = 1000
; Path to dataset used for evaluation
map_dir = "pufferlib/resources/drive/binaries/carla"
backend = PufferEnv
; WOSAC (Waymo Open Sim Agents Challenge) evaluation settings
; If True, enables evaluation on realism metrics each time we save a checkpoint
wosac_realism_eval = False
wosac_num_rollouts = 32  ; Number of policy rollouts per scene
wosac_init_steps = 10 ; When to start the simulation
wosac_num_agents = 256  ; Total number of WOSAC agents to evaluate
wosac_control_mode = "control_wosac"  ; Control the tracks to predict
wosac_init_mode = "create_all_valid"  ; Initialize from the tracks to predict
wosac_goal_behavior = 2  ; Stop when reaching the goal
wosac_goal_radius = 2.0 ; Can shrink goal radius for WOSAC evaluation
wosac_sanity_check = False
wosac_aggregate_results = True ; Only return aggregate results across all scenes
; If True, enable human replay evaluation (pair policy-controlled agent with human replays)
human_replay_eval = False
human_replay_control_mode = "control_sdc_only" ; Control only the self-driving car
human_replay_num_agents = 64 ; This equals the number of scenarios, since we control one agent in each

[sweep.train.learning_rate]
distribution = log_normal
min = 0.001
mean = 0.003
max = 0.005
scale = auto

[sweep.train.ent_coef]
distribution = log_normal
min = 0.001
mean = 0.005
max = 0.01
scale = auto

[sweep.env.goal_radius]
distribution = uniform
min = 2.0
max = 20.0
mean = 10.0
scale = auto

[sweep.env.reward_ade]
distribution = uniform
min = -0.1
max = 0.0
mean = -0.02
scale = auto

[sweep.env.reward_goal_post_respawn]
distribution = uniform
min = 0.0
max = 1.0
mean = 0.5
scale = auto

[controlled_exp.train.learning_rate]
values = [0.001, 0.003, 0.01]

[controlled_exp.train.ent_coef]
values = [0.01, 0.005]
