; Configuration for driving behaviour evaluation maps and rewards.
; Currently evaluates 5 broad driving behaviours: lead vehicle interaction, lane change, dense traffic, obstacles, vulnerable road user interactions (VRUs).
; Currently uses safe reward conditioning values for evaluation

[eval_lead_vehicle_interaction]
map_dir = "resources/drive/binaries/lead_vehicle_interaction"
human_replay_eval = True
render_eval = True
episode_length = 91

[eval_lane_change]
map_dir = "resources/drive/binaries/lane_change"
human_replay_eval = True
render_eval = True
episode_length = 91

[eval_dense_traffic]
map_dir = "resources/drive/binaries/dense_traffic"
human_replay_eval = True
render_eval = True
episode_length = 91

[eval_obstacles]
map_dir = "resources/drive/binaries/obstacles"
human_replay_eval = True
render_eval = True
episode_length = 91

[eval_vru_interaction]
map_dir = "resources/drive/binaries/vru_interaction"
human_replay_eval = True
render_eval = True
episode_length = 91

[eval_driving_rewards]
; Reward conditioning values (min=max to fix the value).
; Names match the env reward_bound_* keys.
; High penalties for unsafe behavior
collision = -3.0
offroad = -3.0
overspeed = -1.0
traffic_light = -1.0
reverse = -0.0075
comfort = -0.1

; Standard driving rewards
goal_radius = 8.0
lane_align = 0.0025
lane_center = -0.00075
velocity = 0.005
center_bias = 0.0
vel_align = 1.0
timestep = -0.00005

; Neutral scaling factors
throttle = 1.0
steer = 1.0
acc = 1.0
