"""Extract vehicle dimensions from a running CARLA server (0.9.15) and derive
PufferDrive bicycle-model parameters.

Spawns every vehicle.* blueprint once, reads the bounding box for
length/width/height and the wheel physics for the wheelbase (front/rear axle
positions projected onto the vehicle forward axis). Also reports the rear-axle
offset from the bounding-box center, since PufferDrive's sim position is the
box center, and the wheelbase/length ratio to compare against the hardcoded
0.6 factor in drive.h.

Usage (needs the official carla==0.9.15 client matching the running server):
    python scripts/extract_carla_vehicle_dims.py \
        [--host localhost] [--port 2000] \
        [--out scripts/carla_vehicle_dims.json] \
        [--emit-c pufferlib/ocean/drive/carla_vehicle_dims.h]

The --emit-c header is consumed by the eval-mode spawn path in drive.h.
"""

import argparse
import json
import math

import carla

WHEEL_POSITION_CM_TO_M = 0.01
MIN_PLAUSIBLE_WHEELBASE_M = 0.3
# Assets whose bounding box contradicts their own wheel geometry (bbox width
# ~1.5x wheel track; a real Fuso Rosa is 2.0 m wide, the asset reports 3.94).
BROKEN_BLUEPRINT_IDS = {"vehicle.mitsubishi.fusorosa"}


def dot(vec_a, vec_b):
    return vec_a.x * vec_b.x + vec_a.y * vec_b.y + vec_a.z * vec_b.z


def get_attr(blueprint, name, default=""):
    if blueprint.has_attribute(name):
        return blueprint.get_attribute(name).as_str()
    return default


def get_int_attr(blueprint, name, default=0):
    if blueprint.has_attribute(name):
        return blueprint.get_attribute(name).as_int()
    return default


def compute_wheelbase(actor):
    """Wheelbase and rear-axle-to-bbox-center offset (meters) from wheel
    world positions; (None, None) when the reported geometry is implausible."""
    transform = actor.get_transform()
    forward = transform.get_forward_vector()
    wheels = actor.get_physics_control().wheels
    if len(wheels) < 2:
        return None, None
    wheel_projections = [dot(wheel.position, forward) * WHEEL_POSITION_CM_TO_M for wheel in wheels]
    axle_split = sum(wheel_projections) / len(wheel_projections)
    front_axle = [p for p in wheel_projections if p >= axle_split]
    rear_axle = [p for p in wheel_projections if p < axle_split]
    if not front_axle or not rear_axle:
        return None, None
    wheelbase = sum(front_axle) / len(front_axle) - sum(rear_axle) / len(rear_axle)
    bbox_center_world = carla.Location(actor.bounding_box.location)
    transform.transform(bbox_center_world)
    rear_axle_behind_center = dot(bbox_center_world, forward) - sum(rear_axle) / len(rear_axle)
    if not math.isfinite(wheelbase) or wheelbase < MIN_PLAUSIBLE_WHEELBASE_M:
        return None, None
    return wheelbase, rear_axle_behind_center


def measure_blueprint(world, blueprint, spawn_transform):
    actor = world.try_spawn_actor(blueprint, spawn_transform)
    if actor is None:
        world.wait_for_tick()
        actor = world.try_spawn_actor(blueprint, spawn_transform)
    if actor is None:
        return None
    try:
        world.wait_for_tick()
        extent = actor.bounding_box.extent
        length = 2.0 * extent.x
        width = 2.0 * extent.y
        height = 2.0 * extent.z
        wheelbase, rear_axle_behind_center = compute_wheelbase(actor)
        wheelbase_is_fallback = wheelbase is None or wheelbase > length
        if wheelbase_is_fallback:
            wheelbase = 0.6 * length
            rear_axle_behind_center = None
        return {
            "id": blueprint.id,
            "base_type": get_attr(blueprint, "base_type"),
            "special_type": get_attr(blueprint, "special_type"),
            "number_of_wheels": get_int_attr(blueprint, "number_of_wheels"),
            "length_m": round(length, 3),
            "width_m": round(width, 3),
            "height_m": round(height, 3),
            "wheelbase_m": round(wheelbase, 3),
            "wheelbase_ratio": round(wheelbase / length, 3) if length > 0 else None,
            "rear_axle_behind_center_m": (
                round(rear_axle_behind_center, 3) if rear_axle_behind_center is not None else None
            ),
            "wheelbase_is_fallback": wheelbase_is_fallback,
        }
    finally:
        actor.destroy()


def emit_c_header(rows, path):
    lines = [
        "// Generated by scripts/extract_carla_vehicle_dims.py from CARLA 0.9.15. Do not edit.",
        "// Fields: blueprint id, length_m, width_m, height_m, wheelbase_m",
        "typedef struct CarlaVehicleDims {",
        "    const char *blueprint_id;",
        "    float length_m;",
        "    float width_m;",
        "    float height_m;",
        "    float wheelbase_m;",
        "} CarlaVehicleDims;",
        "",
        "static const CarlaVehicleDims CARLA_VEHICLE_DIMS[] = {",
    ]
    for row in rows:
        lines.append(
            f'    {{"{row["id"]}", {row["length_m"]:.3f}f, {row["width_m"]:.3f}f,'
            f' {row["height_m"]:.3f}f, {row["wheelbase_m"]:.3f}f}},'
        )
    lines += [
        "};",
        "",
        "#define CARLA_VEHICLE_DIMS_COUNT"
        f" {len(rows)}",
        "",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default="localhost")
    parser.add_argument("--port", type=int, default=2000)
    parser.add_argument("--out", default="scripts/carla_vehicle_dims.json")
    parser.add_argument("--emit-c", default=None)
    args = parser.parse_args()

    client = carla.Client(args.host, args.port)
    client.set_timeout(20.0)
    world = client.get_world()
    spawn_points = world.get_map().get_spawn_points()
    if not spawn_points:
        raise RuntimeError("Current CARLA map has no spawn points")
    spawn_transform = spawn_points[0]
    spawn_transform.location.z += 1.0

    blueprints = sorted(world.get_blueprint_library().filter("vehicle.*"), key=lambda bp: bp.id)
    print(f"Measuring {len(blueprints)} vehicle blueprints on map {world.get_map().name}")

    rows = []
    for blueprint in blueprints:
        if blueprint.id in BROKEN_BLUEPRINT_IDS:
            print(f"[skip] {blueprint.id}: known broken bounding box")
            continue
        row = measure_blueprint(world, blueprint, spawn_transform)
        if row is None:
            print(f"[skip] could not spawn {blueprint.id}")
            continue
        rows.append(row)

    rows.sort(key=lambda r: (r["base_type"], r["id"]))
    header = (
        f"{'blueprint':44s} {'type':11s} {'whl':>3s} {'len':>6s} {'wid':>6s}"
        f" {'hgt':>6s} {'wbase':>6s} {'ratio':>6s} {'raxle':>6s}"
    )
    print(header)
    print("-" * len(header))
    for r in rows:
        rear_axle = f"{r['rear_axle_behind_center_m']:6.2f}" if r["rear_axle_behind_center_m"] is not None else "     -"
        fallback_mark = " (fallback wheelbase)" if r["wheelbase_is_fallback"] else ""
        print(
            f"{r['id']:44s} {r['base_type']:11s} {r['number_of_wheels']:3d} {r['length_m']:6.2f}"
            f" {r['width_m']:6.2f} {r['height_m']:6.2f} {r['wheelbase_m']:6.2f}"
            f" {r['wheelbase_ratio']:6.2f} {rear_axle}{fallback_mark}"
        )

    with open(args.out, "w") as f:
        json.dump(rows, f, indent=2)
    print(f"\nWrote {len(rows)} entries to {args.out}")
    if args.emit_c:
        emit_c_header(rows, args.emit_c)
        print(f"Wrote C table to {args.emit_c}")


if __name__ == "__main__":
    main()
