agent_index: null
controlled_exp:
  train:
    ent_coef:
      values:
      - 0.01
      - 0.005
    learning_rate:
      values:
      - 0.001
      - 0.003
      - 0.01
env:
  action_type: discrete
  collision_behavior: 1
  compute_eval_metrics: false
  control_mode: control_vehicles
  dt: 0.1
  dynamics_model: jerk
  goal_regen_mode: finite
  goal_source: route
  goal_radius: 2.0
  goal_speed: 1000.0
  inactive_agent_threshold: 0.4
  init_mode: create_all_valid
  init_step: 0
  map_dir: "pufferlib/resources/drive/binaries/carla"
  max_agents_per_env: 80
  max_goal_spacing: 40.0
  min_agents_per_env: 1
  min_goal_spacing: 20.0
  non_sdc_controller: policy
  non_vehicle_controller: auto
  num_agents: 2048
  num_maps: 8
  num_goals: 3
  obs_dropout_boundary: 0.0
  obs_dropout_lane: 0.0
  obs_norm_goal_offset_m: 120.0
  obs_norm_road_seg_length_m: 10.0
  obs_norm_road_seg_width_m: 5.0
  obs_norm_veh_length_m: 10.0
  obs_norm_veh_width_m: 5.0
  obs_norm_xy_offset_m: 120.0
  obs_range_partner_m: 120.0
  obs_range_road_behind_m: 30.0
  obs_range_road_front_m: 120.0
  obs_range_road_side_m: 40.0
  obs_range_traffic_control_m: 120.0
  obs_slots_boundary_n: 30
  obs_slots_lane_n: 50
  obs_slots_partners_n: 12
  obs_slots_traffic_controls_n: 4
  offroad_behavior: 1
  partner_blindness_prob: 0.0
  partner_blindness_trigger_prob: 0.0
  phantom_braking_duration: 10
  phantom_braking_prob: 0.0
  phantom_braking_trigger_prob: 0.0
  resample_frequency: 102400
  reward_ade: 0.0
  reward_center_bias: 0.0
  reward_collision: 1.5
  reward_comfort: 0.5
  reward_conditioning: false
  reward_goal: 0.2
  reward_lane_align: 0.5
  reward_lane_center: 0.05
  reward_offroad: 1.5
  reward_overspeed: 0.1
  reward_randomization: false
  reward_reverse: 0.005
  reward_stop_line: 1.0
  reward_timestep: 0.0
  reward_vel_align: 1.0
  reward_velocity: 0.1
  scenario_length: 1024
  sdc_controller: policy
  simulation_mode: gigaflow
  spawn_initial_speed: 0.0
  goal_regen_mode: finite
  goal_source: route
  termination_mode: 1
  traffic_light_behavior: 1
  use_map_cache: 1
env_name: puffer_drive
eval_simulation: null
fps: 15
gif_path: eval.gif
git:
  commit_hash: 9d3fcc5c09db50b9674a374b8c3404b6349c4cb5
load_id: null
load_model_path: null
local_rank: 0
max_runs: 200
max_suggestion_cost: 3600
neptune: false
neptune_name: pufferai
neptune_project: ablations
no_model_upload: {}
num_scenarios: 3
package: ocean
policy:
  actor_hidden_size: 512
  actor_num_layers: 0
  backbone_activation: gelu
  backbone_hidden_size: 512
  backbone_layer_norm: false
  backbone_num_layers: 2
  boundary_input_size: 128
  context_input_size: 128
  critic_hidden_size: 512
  critic_num_layers: 0
  ego_input_size: 128
  encoder_activation: relu
  encoder_layer_norm: true
  lane_input_size: 128
  mask_padded_features: false
  partner_input_size: 128
  shared_network: true
  traffic_control_input_size: 128
policy_name: Drive
render: 0
render_mode: auto
rnn:
  hidden_size: 512
  input_size: 512
rnn_name: null
run_name: rew-dense-seed4
save_frames: 0
sweep:
  downsample: 10
  goal: maximize
  method: Protein
  metric: score
tag: null
tb: false
train:
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  adv_filter_ewma_beta: 0.25
  adv_filter_threshold_scale: 0.01
  adv_sampling_prio_alpha: 0.8499999999999999
  adv_sampling_prio_beta0: 0.8499999999999999
  amp: true
  anneal_lr: true
  batch_size: auto
  bptt_horizon: 128
  checkpoint_interval: 50
  clip_coef: 0.2
  compile: true
  compile_fullgraph: false
  compile_mode: default
  cpu_offload: false
  data_dir: /pufferdrive/training_output/
  device: cuda
  ent_coef: 0.01
  gae_lambda: 0.95
  gamma: 0.999
  learning_rate: 0.0005
  max_grad_norm: 0.5
  max_minibatch_size: 98304
  minibatch_size: 98304
  name: pufferai
  normalize_rewards: true
  obs_only: true
  optimizer: adamw
  precision: bfloat16
  project: ablations
  render: false
  render_interval: 1000
  render_map: none
  resume_state_path: null
  seed: 4
  show_grid: false
  show_human_logs: true
  show_lasers: false
  torch_deterministic: false
  total_timesteps: 10000000000
  update_epochs: 2
  use_rnn: false
  vf_clip_coef: null
  vf_coef: 0.5
  vtrace_c_clip: 1
  vtrace_rho_clip: 1
vec:
  backend: Multiprocessing
  batch_size: auto
  num_envs: 24
  num_workers: auto
  seed: 42
  zero_copy: true
video_path: videos
wandb: true
wandb_group: pr-smoke-runs
wandb_project: pr-smoke-runs
