/*
 * shaders.h — externs for SPIR-V blobs generated at build time.
 *
 * The actual byte arrays live in shaders.c, which is GENERATED by
 * shaders/build_shaders.sh as part of the extension build. Don't commit
 * shaders.c — it's a build artifact and changes whenever the .vert/.frag
 * sources change.
 *
 * Build script flow:
 *   1. glslangValidator -V *.vert *.frag -o *.spv
 *   2. xxd-style hex dump → shaders.c with one const uint32_t array per shader
 *
 * If you see a linker error about undefined references to *_spv, the
 * build script didn't run. Either run shaders/build_shaders.sh manually
 * or rebuild via setup.py (which invokes it as a pre-build step).
 */

#ifndef TRAJVIZ_SHADERS_H
#define TRAJVIZ_SHADERS_H

#include <stddef.h>
#include <stdint.h>

extern const uint32_t polyline_vert_spv[];
extern const size_t polyline_vert_spv_size; /* in bytes */

extern const uint32_t polyline_frag_spv[];
extern const size_t polyline_frag_spv_size;

extern const uint32_t agent_box_vert_spv[];
extern const size_t agent_box_vert_spv_size;

extern const uint32_t agent_box_frag_spv[];
extern const size_t agent_box_frag_spv_size;

#endif
