name: render-ci

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-render:
    name: test-render - ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Pre-install cleanup to free space
      - name: Free up disk space (before install)
        run: |
          echo "Before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost
          sudo apt clean
          echo "After cleanup:"
          df -h

      - name: Install system dependencies for headless rendering
        run: |
          sudo apt update
          sudo apt install -y ffmpeg xvfb build-essential

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install pufferlib
        run: pip install -e .

      - name: Compile C extensions
        run: python setup.py build_ext --inplace --force

      - name: Run render test
        run: python tests/test_drive_render.py
        timeout-minutes: 15

      # Post-test cleanup (good practice if multiple workflows run)
      - name: Free up disk space (after test)
        if: always()
        run: |
          echo "Cleaning up after tests..."
          sudo rm -rf ~/.cache/pip /tmp/* /var/tmp/*
          df -h
